apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    console.openshift.io/plugins: '["crane-ui-plugin"]'
    operatorframework.io/suggested-namespace: openshift-migration
  name: mtk-operator.v99.0.0
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OperatorConfig is the Schema for the operatorconfigs API
      displayName: Operator Config
      kind: OperatorConfig
      name: operatorconfigs.crane.konveyor.io
      version: v1alpha1
  description: OpenShift Crane Operator
  displayName: OpenShift Crane
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - mtk
  - crane
  - MTK
  links:
  - name: Mtk Operator
    url: https://github.com/konveyor/mtk-operator
  maturity: alpha
  provider:
    name: RedHat
  version: 99.0.0
