apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: mtk-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: OperatorConfig is the Schema for the operatorconfigs API
      displayName: Operator Config
      kind: OperatorConfig
      name: operatorconfigs.crane.konveyor.io
      version: v1alpha1
  description: OpenShift Crane Operator
  displayName: OpenShift Crane
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - mtk
  - crane
  - MTK
  links:
  - name: Mtk Operator
    url: https://mtk-operator.domain
  maturity: alpha
  provider:
    name: RedHat
  version: 0.0.0
